/**
 * parseAiResponse.ts
 * Utilities to normalize AI/backend responses before they reach UI components.
 * Rule: no raw JSON should ever be rendered to the user.
 */

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Strip markdown code fences from a string, e.g. ```json ... ``` or ``` ... ```.
 */
export function stripMarkdownCodeFence(input: string): string {
  if (typeof input !== 'string') return '';
  // Remove ```json\n...\n``` or ```\n...\n```
  const fenced = input.replace(/^```(?:json)?\s*\n?([\s\S]*?)\n?```\s*$/s, '$1');
  return fenced.trim();
}

/**
 * Attempt to parse a string as JSON. Returns the parsed value or null.
 */
export function safeJsonParse<T = unknown>(input: unknown): T | null {
  if (input === null || input === undefined) return null;

  // Already an object — return as-is
  if (typeof input === 'object') return input as T;

  if (typeof input !== 'string') return null;

  // Try parsing directly
  try {
    return JSON.parse(input) as T;
  } catch {
    // Try stripping markdown fences, then parse
    try {
      const stripped = stripMarkdownCodeFence(input);
      return JSON.parse(stripped) as T;
    } catch {
      return null;
    }
  }
}

/** Ensure a value is an array of strings. */
function toStringArray(val: unknown): string[] {
  if (Array.isArray(val)) {
    return val.map((item) => (typeof item === 'string' ? item : String(item)));
  }
  if (typeof val === 'string' && val.trim()) {
    // If it looks like it contains meaningful content, wrap it
    if (!val.startsWith('{') && !val.startsWith('[')) {
      return [val];
    }
  }
  return [];
}

/** Ensure a value is a string. */
function toStr(val: unknown, fallback = ''): string {
  if (typeof val === 'string') return val;
  if (typeof val === 'number') return String(val);
  return fallback;
}

/** Ensure a value is a number. */
function toNum(val: unknown, fallback = 0): number {
  if (typeof val === 'number' && !isNaN(val)) return val;
  const parsed = Number(val);
  return isNaN(parsed) ? fallback : parsed;
}

// ─── Response Normalizers ────────────────────────────────────────────────────

export interface NormalizedAnalyzeResponse {
  explicitRequirements: string[];
  impliedCriteria: string[];
  submissionRisks: string[];
  suggestedAngles: string[];
  summary: string;
}

export interface NormalizedGenerateResponse {
  draft: string;
  whyItWorks: string[];
  customize: string[];
}

export interface NormalizedCheckResponse {
  score: number;
  status: string;
  criticalIssues: string[];
  warnings: string[];
  strongPoints: string[];
  fixOrder: string[];
  wordCount: number;
  speakingTimeSeconds: number;
}

export interface NormalizedFullResponse {
  briefAnalysis: NormalizedAnalyzeResponse;
  generatedAnswer: NormalizedGenerateResponse;
  readinessReport: NormalizedCheckResponse;
}

/**
 * Normalize a /api/analyze response.
 * Handles: object, JSON string, fenced JSON string, partial/malformed responses.
 */
export function normalizeAnalyzeResponse(input: unknown): NormalizedAnalyzeResponse {
  const parsed = typeof input === 'object' && input !== null ? input : safeJsonParse(input);

  if (!parsed || typeof parsed !== 'object') {
    return {
      explicitRequirements: [],
      impliedCriteria: [],
      submissionRisks: [],
      suggestedAngles: [],
      summary: typeof input === 'string' && !looksLikeRawJson(input)
        ? input
        : 'LastLook generated feedback, but it could not be fully structured. Try running the review again.',
    };
  }

  const obj = parsed as Record<string, unknown>;

  return {
    explicitRequirements: toStringArray(obj.explicitRequirements),
    impliedCriteria: toStringArray(obj.impliedCriteria),
    submissionRisks: toStringArray(obj.submissionRisks),
    suggestedAngles: toStringArray(obj.suggestedAngles),
    summary: toStr(obj.summary, ''),
  };
}

/**
 * Normalize a /api/generate response.
 */
export function normalizeGenerateResponse(input: unknown): NormalizedGenerateResponse {
  const parsed = typeof input === 'object' && input !== null ? input : safeJsonParse(input);

  if (!parsed || typeof parsed !== 'object') {
    // If it's a plain string and not raw JSON, treat it as the draft
    const draft = typeof input === 'string' && !looksLikeRawJson(input) ? input : '';
    return {
      draft,
      whyItWorks: draft ? ['Generated by AI'] : [],
      customize: [],
    };
  }

  const obj = parsed as Record<string, unknown>;
  const draft = toStr(obj.draft, '');

  return {
    draft,
    whyItWorks: toStringArray(obj.whyItWorks),
    customize: toStringArray(obj.customize),
  };
}

/**
 * Normalize a /api/check response.
 */
export function normalizeCheckResponse(
  input: unknown,
  fallbackWordCount = 0,
  fallbackSpeakingTime = 0
): NormalizedCheckResponse {
  const parsed = typeof input === 'object' && input !== null ? input : safeJsonParse(input);

  if (!parsed || typeof parsed !== 'object') {
    return {
      score: 0,
      status: 'Could not evaluate',
      criticalIssues: [
        'LastLook generated feedback, but it could not be fully structured. Try running the review again.',
      ],
      warnings: [],
      strongPoints: [],
      fixOrder: [],
      wordCount: fallbackWordCount,
      speakingTimeSeconds: fallbackSpeakingTime,
    };
  }

  const obj = parsed as Record<string, unknown>;

  return {
    score: toNum(obj.score, 0),
    status: toStr(obj.status, 'Unknown'),
    criticalIssues: toStringArray(obj.criticalIssues),
    warnings: toStringArray(obj.warnings),
    strongPoints: toStringArray(obj.strongPoints),
    fixOrder: toStringArray(obj.fixOrder),
    wordCount: toNum(obj.wordCount, fallbackWordCount),
    speakingTimeSeconds: toNum(obj.speakingTimeSeconds, fallbackSpeakingTime),
  };
}

/**
 * Normalize a full /api response combining all three sub-responses.
 */
export function normalizeFullResponse(input: unknown): NormalizedFullResponse {
  const parsed = typeof input === 'object' && input !== null ? input : safeJsonParse(input);
  const obj = (parsed && typeof parsed === 'object' ? parsed : {}) as Record<string, unknown>;

  return {
    briefAnalysis: normalizeAnalyzeResponse(obj.briefAnalysis ?? obj),
    generatedAnswer: normalizeGenerateResponse(obj.generatedAnswer ?? obj),
    readinessReport: normalizeCheckResponse(obj.readinessReport ?? obj),
  };
}

// ─── Utility ────────────────────────────────────────────────────────────────

/**
 * Returns true if a string looks like raw JSON (starts with { or [).
 * Used to avoid rendering raw JSON as user-facing text.
 */
export function looksLikeRawJson(input: string): boolean {
  const trimmed = input.trim();
  return (trimmed.startsWith('{') || trimmed.startsWith('[')) && (trimmed.endsWith('}') || trimmed.endsWith(']'));
}
